"""
preflight.py -- run this before sending the handoff to anyone.

    python preflight.py                 check ../ForenXAI_UI_Handoff
    python preflight.py --out PATH      check a build somewhere else

make_handoff.py runs the panel suite inside the copy, which proves the code
imports and the panels build. It does not prove the things that go wrong
when a folder is zipped, uploaded, downloaded and unzipped by someone else:
a corpus that verifies against nothing because the cache was pruned, a
model file that never made it, a document whose quotes have drifted since
the corpus was written.

Every check here failed at least once during development. That is the bar
for being in this file -- not "might be nice to confirm".
"""
import argparse
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FAIL = []
WARN = []


def check(name, ok, detail=""):
    print(f"  {'pass' if ok else 'FAIL'}  {name}")
    if not ok:
        FAIL.append(name)
        if detail:
            print(f"        {detail}")


def warn(name, ok, detail=""):
    if not ok:
        WARN.append(name)
        print(f"  warn  {name}")
        if detail:
            print(f"        {detail}")


def section(title):
    print(f"\n{title}\n{'-' * len(title)}")


# What goes where. Kept beside the payload checks in section A, so the
# manifest and the checks cannot end up describing different folders.
GROUPS = (
    ("Tab 1 - forensic analysis", ("forensic_tab",)),
    ("Tab 2 - renderer and notes", ("xai_tab/*",)),
    ("Tab 2 - model bundle", ("xai_tab/models",)),
    ("Tab 2 - TreeSHAP reference", ("xai_tab/artifacts",)),
    ("Tab 2 - knowledge corpus", ("xai_tab/knowledge",)),
    ("Shared - services", ("services",)),
    ("Tab 2 - exported LLM (optional)", ("xai_tab/models/*.gguf",)),
    ("Shared - sample data", ("sample_data",)),
    # Every file at the root, not a list of their names. Naming them is how
    # this manifest has now drifted twice -- once when UI_BACKEND_MAP.md was
    # added to a tab, once when START_HERE.md was added here and OLLAMA.md
    # moved out. A count that silently omits a file is worse than no count.
    ("Shared - tools and docs", ("./*",)),
)


def inventory(out, rel):
    """(path, bytes) for a file, a directory tree, or "dir/*".

    The "dir/*" form takes only the files sitting directly in that
    directory, which is how a tab's own renderer and notes are counted
    without also counting the 100 MB of corpus beneath it -- and without
    a list of filenames that goes stale the moment one is added.
    """
    if rel.endswith("/*.gguf"):
        d = os.path.join(out, rel[:-7])
        if not os.path.isdir(d):
            return []
        return [(f"{rel[:-7]}/{f}", os.path.getsize(os.path.join(d, f)))
                for f in sorted(os.listdir(d)) if f.endswith(".gguf")]
    if rel == "./*":
        return [(f, os.path.getsize(os.path.join(out, f)))
                for f in sorted(os.listdir(out))
                if os.path.isfile(os.path.join(out, f))]
    if rel.endswith("/*"):
        d = os.path.join(out, rel[:-2])
        return [(f"{rel[:-2]}/{f}", os.path.getsize(os.path.join(d, f)))
                for f in sorted(os.listdir(d))
                if os.path.isfile(os.path.join(d, f))]
    root = os.path.join(out, rel)
    if os.path.isfile(root):
        return [(rel, os.path.getsize(root))]
    found = []
    for r, _, fs in os.walk(root):
        for f in fs:
            full = os.path.join(r, f)
            found.append((os.path.relpath(full, out).replace(os.sep, "/"),
                          os.path.getsize(full)))
    return found


def write_manifest(out):
    """Write SEND_LIST.md into the payload, generated from the payload.

    A hand-kept list of what to send goes stale the first time the build
    changes and nobody notices, because nothing checks a list. This one is
    regenerated from the folder it describes every time that folder is
    cleared to send, so it is either right or the build did not pass.
    """
    # Create it before taking the inventory, or the manifest cannot count
    # itself: make_handoff.py rebuilds the folder from scratch, so
    # SEND_LIST.md does not exist when the walk runs and the total came out
    # one short of the folder it describes. An exact count is the entire
    # point of this file.
    out_path = os.path.join(out, "SEND_LIST.md")
    if not os.path.exists(out_path):
        open(out_path, "w", encoding="utf-8").close()

    rows, tn, tb = [], 0, 0
    for name, rels in GROUPS:
        files = [f for r in rels for f in inventory(out, r)]
        n, b = len(files), sum(sz for _, sz in files)
        tn, tb = tn + n, tb + b
        rows.append((name, rels, files, n, b))

    lines = [
        "# What is in this folder",
        "",
        "Generated by `preflight.py` from this build, on the build that",
        "passed. Do not edit by hand -- rebuild and re-run instead.",
        "",
        "| Group | Files | Size |",
        "|---|---:|---:|",
    ]
    for name, _, _, n, b in rows:
        lines.append(f"| {name} | {n} | {b / 1048576:.1f} MB |")
    lines.append(f"| **Total** | **{tn}** | **{tb / 1048576:.1f} MB** |")

    lines += ["", "## Every file", ""]
    for name, _, files, _, _ in rows:
        lines += [f"### {name}", "", "```"]
        lines += [f for f, _ in sorted(files)]
        lines += ["```", ""]

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return tn, tb


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(HERE), "ForenXAI_UI_Handoff"))
    args = ap.parse_args()
    out = os.path.abspath(args.out)

    # This script imports from the payload and runs two suites inside it.
    # Both write bytecode, into the very folder section D then checks for
    # bytecode. Judging a build on litter the check itself dropped is worse
    # than not checking: it fails a clean build and teaches you to ignore
    # the result. So nothing writes any.
    sys.dont_write_bytecode = True
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"

    print(f"Checking {out}")
    if not os.path.isdir(out):
        print("  FAIL  the folder does not exist -- run make_handoff.py first")
        return 1

    # ---------------------------------------------------------------
    section("A  PAYLOAD  each tab has the files it loads")
    for rel in (
            "forensic_tab/forensic_tab.py",
            "forensic_tab/README.md",
            "forensic_tab/artifacts/ForenXAI-Multiclass/forensic_tab/model.joblib",
            "forensic_tab/artifacts/ForenXAI-Multiclass/forensic_tab/"
            "frozen_feature_schema_l2.json",
            "xai_tab/xai_tab.py",
            "xai_tab/README.md",
            "xai_tab/RAG_INTEGRATION.md",
            "xai_tab/models/forenxai/XGBoost.pkl",
            "xai_tab/models/forenxai/manifest.json",
            "xai_tab/knowledge/incident_response",
            "xai_tab/knowledge/_sources/manifest.json",
            "services/panels_service.py",
            "services/source_guard.py",
            "smoke_test.py",
            "requirements.txt",
            "README.md"):
        check(rel, os.path.exists(os.path.join(out, rel)))

    # ---------------------------------------------------------------
    section("B  CORPUS  every class maps to a document that is on disk")
    sys.path.insert(0, out)
    cwd = os.getcwd()
    os.chdir(out)
    try:
        for mod in [m for m in list(sys.modules)
                    if m.startswith(("services", "fetch_knowledge"))]:
            del sys.modules[mod]
        from services.panels_service import (KNOWLEDGE_MAP, KNOWLEDGE_DIR,
                                             bundle_available)
        import fetch_knowledge as fk

        check("all 16 classes are mapped", len(KNOWLEDGE_MAP) == 16,
              f"{len(KNOWLEDGE_MAP)} entries")
        missing = [e["doc"] for e in KNOWLEDGE_MAP.values()
                   if not os.path.isfile(
                       os.path.join(KNOWLEDGE_DIR, e["doc"]))]
        check("every mapped document is present", not missing, str(missing[:4]))

        # The corpus two modules disagreeing about is the failure that
        # renders panels with no check behind the quotes.
        check("fetch_knowledge and panels_service agree on the corpus",
              os.path.normcase(os.path.abspath(fk.KNOWLEDGE))
              == os.path.normcase(os.path.abspath(KNOWLEDGE_DIR)),
              f"{fk.KNOWLEDGE} != {KNOWLEDGE_DIR}")

        ok, detail = bundle_available()
        check("the model bundle loads and its manifest verifies", ok, detail)

        # Tab 1 loads a different file from a different folder, and until
        # this ran nothing proved it could -- section A only checked the
        # path existed.
        from services.model_service import discover_models, load_model
        found = discover_models()
        check("the forensic tab discovers its model",
              "ForenXAI-Multiclass" in found, str(list(found)))
        try:
            load_model("ForenXAI-Multiclass")
            check("the forensic tab's model loads", True)
        except Exception as e:
            check("the forensic tab's model loads", False, f"{type(e).__name__}: {e}")

        # ------------------------------------------------------------
        section("C  SOURCES  quotes verify, and against what")
        cache = os.path.join(KNOWLEDGE_DIR, "_sources", ".cache")
        pdfs = [f for f in os.listdir(os.path.join(KNOWLEDGE_DIR, "_sources"))
                if f.lower().endswith(".pdf")]
        has_cache = os.path.isdir(cache) and os.listdir(cache)
        check("the extracted-text cache shipped", bool(has_cache),
              "without it every quote fails and every document is quarantined")
        warn("the source PDFs shipped", bool(pdfs),
             "a --no-sources build verifies against the cache only; the "
             "recipient cannot re-derive a quote themselves")

        from services.panels_service import build_panels
        sample = os.path.join(out, "sample_data", "sample_flows_full.csv")
        if not os.path.isfile(sample):
            sample = os.path.join(out, "sample_data", "sample_flows.csv")
        res = build_panels(sample, "preflight.pcap")
        check("a capture analyses without narration", "error" not in res,
              str(res.get("error"))[:120])

        rec = res.get("recommend") or {}
        check("no retrieved document is quarantined",
              not rec.get("unverified_documents"),
              str(rec.get("unverified_documents"))[:160])
        check("no mapped document is missing",
              not rec.get("missing_documents"),
              str(rec.get("missing_documents"))[:160])
        check("panel 3 retrieved something", bool(rec.get("sections")))
        check("every reference marker resolves",
              all(r.get("citation") for r in rec.get("reference_map") or []))

        weak = [s["source"] for s in rec.get("sections") or []
                if s.get("verified_against") == "cache"]
        warn("every quote verified against its PDF, not the cache", not weak,
             f"{len(weak)} section(s) fell back to the cache")
    finally:
        os.chdir(cwd)

    # ---------------------------------------------------------------
    # Before section D, because running the suites inside the copy creates
    # bytecode there -- this script must not fail the build for its own
    # side effect, and must not leave that side effect behind either.
    section("D  HYGIENE  nothing of ours that should not travel")
    # A developer's own path, shipped. Three tools carried the author's
    # desktop spelled out -- and a tab README told the reader to run one
    # of them, so it would have failed on the first machine to open it.
    import re as _re
    drive = _re.compile(r"['\"][A-Za-z]:[\\\\/]{1,2}Users[\\\\/]{1,2}")
    leaked = []
    for r, ds, fs in os.walk(out):
        ds[:] = [d for d in ds if d not in ("__pycache__", "_sources")]
        for f in fs:
            if not f.endswith((".py", ".md")):
                continue
            try:
                body = open(os.path.join(r, f), encoding="utf-8").read()
            except OSError:
                continue
            if drive.search(body):
                leaked.append(os.path.relpath(os.path.join(r, f), out))
    check("no absolute developer path is shipped", not leaked,
          ", ".join(leaked[:4]))
    for junk in ("__pycache__", "ForenXAI_Cases", ".git"):
        check(f"no {junk}/ in the payload",
              not os.path.exists(os.path.join(out, junk)))

    # ---------------------------------------------------------------
    section("E  SELF-TEST  the copy proves itself in its own directory")
    for script in ("smoke_test.py", "test_panels_suite.py"):
        r = subprocess.run([sys.executable, script], cwd=out,
                           capture_output=True, text=True)
        line = next((l for l in r.stdout.splitlines()
                     if "checks passed" in l or "checks failed" in l), "")
        check(f"{script}: {line.strip() or 'no result line'}",
              r.returncode == 0,
              (r.stderr.splitlines() or [""])[-1][:160])

    # A case workspace is written by the suites regardless; remove it so the
    # folder is exactly what make_handoff.py built.
    shutil.rmtree(os.path.join(out, "ForenXAI_Cases"), ignore_errors=True)

    n_files, n_bytes = write_manifest(out)
    print(f"\n  payload {n_files} files, {n_bytes / 1048576:.1f} MB")
    print("  wrote SEND_LIST.md")

    # ---------------------------------------------------------------
    print()
    if FAIL:
        print(f"{len(FAIL)} check(s) FAILED -- do not send this build.")
        for f in FAIL:
            print(f"  - {f}")
        return 1
    if WARN:
        print(f"Ready to send, with {len(WARN)} thing(s) to say out loud:")
        for w in WARN:
            print(f"  - {w}")
    else:
        print("Ready to send.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
