import os
import glob
import subprocess

import numpy as np
import pandas as pd

from services.config import (
    CICFLOWMETER_JAR,
    CICFLOWMETER_JAVA,
    CICFLOWMETER_NATIVE_DIR,
    CICFLOWMETER_EXECUTABLE,
)


# ============================================================
# SUPPORTED CAPTURE FILES
# ============================================================

SUPPORTED_PCAP_EXTENSIONS = (
    ".pcap",
    ".pcapng",
)


def validate_pcap_file(pcap_path):
    """
    Validate that the supplied evidence is a supported
    PCAP / PCAPNG file.
    """

    if not pcap_path:
        raise ValueError(
            "No PCAP file was supplied."
        )

    if not os.path.isfile(pcap_path):
        raise FileNotFoundError(
            f"PCAP file does not exist:\n{pcap_path}"
        )

    extension = os.path.splitext(
        pcap_path
    )[1].lower()

    if extension not in SUPPORTED_PCAP_EXTENSIONS:
        raise ValueError(
            "Unsupported capture format.\n\n"
            "ForenXAI accepts:\n"
            "  .pcap\n"
            "  .pcapng"
        )

    if os.path.getsize(pcap_path) == 0:
        raise ValueError(
            "The supplied PCAP file is empty."
        )


# ============================================================
# CICFLOWMETER COMMAND
# ============================================================

def _build_cicflowmeter_command(
    pcap_path,
    output_dir
):
    """
    Build the CICFlowMeter v4 command.

    Priority:

    1. CICFLOWMETER_EXECUTABLE
    2. CICFLOWMETER_JAR

    For the official CICFlowMeter v4 command class,
    the expected arguments are:

        <input-pcap> <output-directory>
    """

    # --------------------------------------------------------
    # Direct executable / BAT / CMD
    # --------------------------------------------------------

    if CICFLOWMETER_EXECUTABLE:

        executable = os.path.abspath(
            os.path.expandvars(
                os.path.expanduser(
                    CICFLOWMETER_EXECUTABLE
                )
            )
        )

        if not os.path.exists(executable):
            raise FileNotFoundError(
                "CICFlowMeter executable was configured but "
                "could not be found:\n\n"
                f"{executable}"
            )

        extension = os.path.splitext(
            executable
        )[1].lower()

        if extension in (".bat", ".cmd"):

            return [
                "cmd",
                "/c",
                executable,
                pcap_path,
                output_dir,
            ]

        return [
            executable,
            pcap_path,
            output_dir,
        ]

    # --------------------------------------------------------
    # JAR
    # --------------------------------------------------------

    if CICFLOWMETER_JAR:

        jar_path = os.path.abspath(
            os.path.expandvars(
                os.path.expanduser(
                    CICFLOWMETER_JAR
                )
            )
        )

        if not os.path.isfile(jar_path):
            raise FileNotFoundError(
                "CICFlowMeter JAR was configured but "
                "could not be found:\n\n"
                f"{jar_path}"
            )

        command = [
            CICFLOWMETER_JAVA,
        ]

        # jNetPcap native library directory
        if CICFLOWMETER_NATIVE_DIR:

            native_dir = os.path.abspath(
                os.path.expandvars(
                    os.path.expanduser(
                        CICFLOWMETER_NATIVE_DIR
                    )
                )
            )

            if not os.path.isdir(native_dir):
                raise FileNotFoundError(
                    "CICFlowMeter native jNetPcap directory "
                    "does not exist:\n\n"
                    f"{native_dir}"
                )

            command.extend([
                f"-Djava.library.path={native_dir}"
            ])

        command.extend([
            "-jar",
            jar_path,
            pcap_path,
            output_dir,
        ])

        return command

    raise RuntimeError(
        "CICFlowMeter v4 is not configured.\n\n"
        "Configure either:\n"
        "  CICFLOWMETER_EXECUTABLE\n"
        "or:\n"
        "  CICFLOWMETER_JAR\n\n"
        "Example:\n"
        "  CICFLOWMETER_JAR=C:\\\\Tools\\\\CICFlowMeter\\\\CICFlowMeter-4.0.jar"
    )


# ============================================================
# OUTPUT FILE DISCOVERY
# ============================================================

def _find_generated_csv(
    pcap_path,
    output_dir
):
    """
    Locate the CSV generated by CICFlowMeter.

    Official CICFlowMeter v4 uses:

        <pcap filename>_Flow.csv
    """

    base_name = os.path.basename(
        pcap_path
    )

    expected_path = os.path.join(
        output_dir,
        f"{base_name}_Flow.csv"
    )

    if os.path.isfile(expected_path):
        return expected_path

    # Some CICFlowMeter builds may remove the original
    # extension before constructing the output filename.
    stem = os.path.splitext(
        base_name
    )[0]

    alternative_paths = [
        os.path.join(
            output_dir,
            f"{stem}_Flow.csv"
        ),
        os.path.join(
            output_dir,
            f"{base_name}_ISCX.csv"
        ),
        os.path.join(
            output_dir,
            f"{stem}_ISCX.csv"
        ),
    ]

    for path in alternative_paths:
        if os.path.isfile(path):
            return path

    # Final fallback: search for generated CSV files.
    csv_files = glob.glob(
        os.path.join(
            output_dir,
            "*.csv"
        )
    )

    if len(csv_files) == 1:
        return csv_files[0]

    if not csv_files:
        raise FileNotFoundError(
            "CICFlowMeter completed but did not "
            "generate a CSV flow file.\n\n"
            f"Expected output directory:\n{output_dir}"
        )

    raise FileNotFoundError(
        "CICFlowMeter generated CSV files, but "
        "ForenXAI could not uniquely identify the "
        "correct output file.\n\n"
        "Generated files:\n"
        + "\n".join(csv_files)
    )


# ============================================================
# RUN CICFLOWMETER
# ============================================================

def run_cicflowmeter(
    pcap_path,
    output_dir,
    log_fn=None
):
    """
    Run CICFlowMeter v4 against a single PCAP / PCAPNG.

    Returns:
        generated_csv_path
    """

    validate_pcap_file(
        pcap_path
    )

    os.makedirs(
        output_dir,
        exist_ok=True
    )

    command = _build_cicflowmeter_command(
        pcap_path,
        output_dir
    )

    if log_fn:
        log_fn(
            "[+] CICFlowMeter command prepared.",
            "success"
        )

        log_fn(
            "[+] Input capture: "
            + os.path.basename(pcap_path),
            "info"
        )

        log_fn(
            "[+] Flow output directory: "
            + output_dir,
            "info"
        )

    try:

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            cwd=output_dir,
            check=False,
        )

    except FileNotFoundError as exc:

        raise RuntimeError(
            "Unable to start CICFlowMeter.\n\n"
            "Make sure Java/CICFlowMeter is installed "
            "and configured correctly.\n\n"
            f"Command:\n{' '.join(command)}"
        ) from exc

    if result.stdout and log_fn:

        for line in result.stdout.splitlines():

            line = line.strip()

            if line:
                log_fn(
                    "[CICFlowMeter] " + line,
                    "info"
                )

    if result.stderr and log_fn:

        for line in result.stderr.splitlines():

            line = line.strip()

            if line:
                log_fn(
                    "[CICFlowMeter] " + line,
                    "info"
                )

    if result.returncode != 0:

        error_output = (
            result.stderr.strip()
            or result.stdout.strip()
            or "No diagnostic output was provided."
        )

        raise RuntimeError(
            "CICFlowMeter execution failed.\n\n"
            f"Exit code: {result.returncode}\n\n"
            f"{error_output}"
        )

    generated_csv = _find_generated_csv(
        pcap_path,
        output_dir
    )

    if log_fn:
        log_fn(
            "[+] CICFlowMeter generated flow CSV: "
            + generated_csv,
            "success"
        )

    return generated_csv


# ============================================================
# LOAD CICFLOWMETER CSV
# ============================================================

def load_cicflowmeter_csv(
    csv_path
):
    """
    Load a CICFlowMeter-generated CSV into a DataFrame.
    """

    if not os.path.isfile(csv_path):
        raise FileNotFoundError(
            f"CICFlowMeter CSV does not exist:\n{csv_path}"
        )

    df = pd.read_csv(
        csv_path,
        low_memory=False
    )

    if df.empty:
        return df

    # CICFlowMeter datasets can contain leading/trailing
    # whitespace in column names depending on the version
    # or source dataset.
    df.columns = [
        str(column).strip()
        for column in df.columns
    ]

    return df


# ============================================================
# DATA CLEANING
# ============================================================

def clean_features(df):
    """
    Generic cleaning for CICFlowMeter feature data.

    This intentionally does NOT rename features.

    The trained model's feature_names_in_ is the authoritative
    inference schema.
    """

    df = df.copy()

    # --------------------------------------------------------
    # Remove accidental whitespace from column names
    # --------------------------------------------------------

    df.columns = [
        str(column).strip()
        for column in df.columns
    ]

    # --------------------------------------------------------
    # Replace CICFlowMeter invalid numeric values
    # --------------------------------------------------------

    df.replace(
        [np.inf, -np.inf],
        np.nan,
        inplace=True
    )

    # --------------------------------------------------------
    # Convert object columns to numeric when possible
    # --------------------------------------------------------

    for column in df.columns:

        if df[column].dtype == "object":

            converted = pd.to_numeric(
                df[column],
                errors="coerce"
            )

            # Only replace the original column if the
            # conversion actually produced numeric values.
            if converted.notna().sum() > 0:
                df[column] = converted

    # --------------------------------------------------------
    # Fill numeric missing values
    # --------------------------------------------------------

    numeric_columns = df.select_dtypes(
        include=[np.number]
    ).columns

    for column in numeric_columns:

        df[column] = df[column].fillna(0)

    return df


# ============================================================
# COMPLETE EXTRACTION
# ============================================================

def extract_flows_from_pcap(
    pcap_path,
    case_dir,
    log_fn=None
):
    """
    Complete PCAP -> CICFlowMeter -> DataFrame operation.

    Returns:

        df,
        generated_csv_path
    """

    csv_path = run_cicflowmeter(
        pcap_path=pcap_path,
        output_dir=case_dir,
        log_fn=log_fn,
    )

    df = load_cicflowmeter_csv(
        csv_path
    )

    if df.empty:
        raise ValueError(
            "CICFlowMeter generated an empty flow CSV. "
            "No network flows were extracted from the "
            "supplied PCAP."
        )

    return df, csv_path