import os
import json

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from services.utils import calculate_sha256

try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False


# ============================================================
# SHAP VALUE NORMALIZATION
# ============================================================

def normalize_shap_values(
    shap_values,
    X,
    predictions
):
    """
    Normalize SHAP output into:

        shape = (n_samples, n_features)

    For classification models, the explanation corresponding
    to each flow's predicted class is selected.

    Supports common SHAP output formats.
    """

    values = np.asarray(shap_values)

    # --------------------------------------------------------
    # SHAP may return:
    #
    # Binary:
    #   (samples, features)
    #
    # Multiclass:
    #   (samples, features, classes)
    # --------------------------------------------------------

    if values.ndim == 2:

        return values

    if values.ndim == 3:

        n_samples = values.shape[0]
        n_features = values.shape[1]
        n_classes = values.shape[2]

        if n_samples != len(X):
            raise ValueError(
                "SHAP output sample count does not match "
                "the inference DataFrame."
            )

        if n_features != len(X.columns):
            raise ValueError(
                "SHAP output feature count does not match "
                "model input feature count."
            )

        # ----------------------------------------------------
        # Select the SHAP class for each prediction.
        #
        # For binary classification this normally selects
        # class 1 when the model predicts 1.
        # ----------------------------------------------------

        class_indices = []

        for prediction in predictions:

            try:
                class_index = int(prediction)
            except (TypeError, ValueError):
                class_index = 0

            if class_index < 0 or class_index >= n_classes:
                class_index = 0

            class_indices.append(
                class_index
            )

        normalized = np.zeros(
            (n_samples, n_features),
            dtype=float
        )

        for i, class_index in enumerate(
            class_indices
        ):

            normalized[i] = values[
                i,
                :,
                class_index
            ]

        return normalized

    raise ValueError(
        "Unsupported SHAP output shape: "
        f"{values.shape}"
    )


# ============================================================
# KERNEL SHAP EXPLANATION
# ============================================================

def generate_shap_explanation(
    model,
    X,
    predictions,
    case_id,
    case_dir,
    log_fn,
    shap_background
):
    """
    Generate Kernel SHAP explanations for the final
    ForenXAI model.

    This implementation is intentionally model-agnostic.

    It explains:

        model.predict_proba(X)

    rather than trying to inspect the internal estimators.

    This is required because the CIDS2018 model is a:

        sklearn.calibration.CalibratedClassifierCV

    Parameters
    ----------
    model:
        Loaded sklearn-compatible classifier.

    X:
        Final model feature DataFrame.

    predictions:
        Predictions generated by model.predict(X).

    case_id:
        Current forensic case ID.

    case_dir:
        Current forensic case directory.

    log_fn:
        GUI logging callback.

    shap_background:
        Frozen Kernel SHAP background loaded from the
        selected model artifact.
    """

    if not SHAP_AVAILABLE:

        log_fn(
            "[!] SHAP is not installed. "
            "Explanation stage skipped.",
            "error"
        )

        return None, None

    if shap_background is None:

        log_fn(
            "[!] SHAP background is not available. "
            "Explanation stage skipped.",
            "error"
        )

        return None, None

    try:

        # ====================================================
        # VALIDATE BACKGROUND
        # ====================================================

        log_fn(
            "[*] Preparing frozen Kernel SHAP background...",
            "info"
        )

        # The stored artifact is SHAP DenseData.
        #
        # KernelExplainer accepts the underlying NumPy
        # matrix, so use .data when available.

        if hasattr(
            shap_background,
            "data"
        ):

            background_data = (
                shap_background.data
            )

        else:

            background_data = (
                np.asarray(
                    shap_background
                )
            )

        background_data = np.asarray(
            background_data,
            dtype=float
        )

        if background_data.ndim != 2:

            raise ValueError(
                "SHAP background must be a "
                "2-dimensional matrix."
            )

        if background_data.shape[1] != len(
            X.columns
        ):

            raise ValueError(
                "SHAP background feature count "
                "does not match model input.\n\n"
                f"Background features: "
                f"{background_data.shape[1]}\n"
                f"Model features: "
                f"{len(X.columns)}"
            )

        log_fn(
            "[+] Frozen SHAP background loaded: "
            f"{background_data.shape[0]} samples × "
            f"{background_data.shape[1]} features.",
            "success"
        )

        # ====================================================
        # KERNEL SHAP
        # ====================================================

        log_fn(
            "[*] Creating Kernel SHAP explainer...",
            "info"
        )

        explainer = shap.KernelExplainer(
            model.predict_proba,
            background_data
        )

        log_fn(
            "[+] Kernel SHAP explainer created.",
            "success"
        )

        # ====================================================
        # GENERATE SHAP VALUES
        # ====================================================

        log_fn(
            "[*] Calculating SHAP values for "
            f"{len(X):,} flow(s)...",
            "info"
        )

        raw_shap_values = explainer.shap_values(
            X,
            nsamples="auto"
        )

        shap_values = normalize_shap_values(
            raw_shap_values,
            X,
            predictions
        )

        if shap_values.shape != (
            len(X),
            len(X.columns)
        ):

            raise ValueError(
                "Normalized SHAP output shape does "
                "not match inference data.\n\n"
                f"SHAP shape: {shap_values.shape}\n"
                f"Expected: "
                f"({len(X)}, {len(X.columns)})"
            )

        # ====================================================
        # PER-FLOW EXPLANATIONS
        # ====================================================

        explanation_records = []

        for i in range(
            len(X)
        ):

            feature_values = X.iloc[i]

            shap_row = shap_values[i]

            ranked_features = sorted(
                zip(
                    X.columns,
                    shap_row
                ),
                key=lambda item: abs(
                    float(item[1])
                ),
                reverse=True
            )

            top_features = []

            for feature, value in (
                ranked_features[:10]
            ):

                top_features.append({
                    "feature": str(feature),
                    "feature_value": str(
                        feature_values[feature]
                    ),
                    "shap_value": float(
                        value
                    )
                })

            explanation_records.append({
                "flow_index": int(i),
                "prediction": str(
                    predictions[i]
                ),
                "top_features": top_features
            })

        # ====================================================
        # SAVE SHAP JSON
        # ====================================================

        shap_path = os.path.join(
            case_dir,
            f"{case_id}_shap.json"
        )

        with open(
            shap_path,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                explanation_records,
                f,
                indent=4
            )

        shap_hash = calculate_sha256(
            shap_path
        )

        # ====================================================
        # GLOBAL SHAP IMPORTANCE
        # ====================================================

        mean_importance = np.mean(
            np.abs(shap_values),
            axis=0
        )

        importance_df = pd.DataFrame({
            "feature": X.columns,
            "importance": mean_importance
        })

        importance_df.sort_values(
            "importance",
            ascending=True,
            inplace=True
        )

        top_global = importance_df.tail(
            15
        )

        fig, ax = plt.subplots(
            figsize=(8, 5)
        )

        ax.barh(
            top_global["feature"],
            top_global["importance"]
        )

        ax.set_title(
            "Global SHAP Feature Importance"
        )

        ax.set_xlabel(
            "Mean |SHAP Value|"
        )

        fig.tight_layout()

        shap_plot_path = os.path.join(
            case_dir,
            f"{case_id}_shap_importance.png"
        )

        fig.savefig(
            shap_plot_path,
            dpi=150
        )

        plt.close(
            fig
        )

        # ====================================================
        # COMPLETE
        # ====================================================

        log_fn(
            "[+] SHAP explanations generated.",
            "success"
        )

        log_fn(
            "[+] SHAP explanation file: "
            + shap_path,
            "success"
        )

        log_fn(
            "[+] SHAP importance chart: "
            + shap_plot_path,
            "success"
        )

        return explanation_records, {
            "shap_path": shap_path,
            "shap_sha256": shap_hash,
            "shap_plot_path": shap_plot_path
        }

    except Exception as e:

        log_fn(
            f"[!] SHAP explanation failed: {e}",
            "error"
        )

        return None, None